CREATE TABLE IF NOT EXISTS messagesaudit (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Message varchar(5000) NOT NULL,
  Metadata varchar(5000) NOT NULL,
  DateTime date NOT NULL,
  ThreadId int(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;