CREATE TABLE IF NOT EXISTS AspNetUserClaims (
  Id int NOT NULL AUTO_INCREMENT,
  UserId varchar(128) NOT NULL,
  ClaimType varchar(256) DEFAULT NULL,
  ClaimValue varchar(256) DEFAULT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_auth_AspNetUsers_UserId FOREIGN KEY (UserId)
  REFERENCES AspNetUsers (Id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 14
AVG_ROW_LENGTH = 1365
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;